# Generated by Django 5.0 on 2026-04-09 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=30, unique=True, verbose_name='Numéro de facture')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventes.vente', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
    ]
