# Generated by Django 5.0 on 2026-04-09 23:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mvt', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement'), ('INVENTAIRE', 'Inventaire')], max_length=20, verbose_name='Type')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix unitaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit', verbose_name='Produit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['produit'], name='stock_mouve_produit_66c825_idx'), models.Index(fields=['type_mvt'], name='stock_mouve_type_mv_7b0166_idx'), models.Index(fields=['-created_at'], name='stock_mouve_created_cc731a_idx')],
            },
        ),
    ]
