# Generated by Django 5.2.13 on 2026-05-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_magasin'),
        ('stock', '0003_mouvementstock_magasin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.magasin', verbose_name='Magasin'),
        ),
    ]
