# Generated by Django 5.0 on 2026-04-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_magasin', models.CharField(default='Magasin Madina', max_length=200, verbose_name='Nom du magasin')),
                ('adresse_magasin', models.TextField(blank=True, verbose_name='Adresse du magasin')),
                ('telephone_magasin', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email_magasin', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('devise', models.CharField(default='GNF', max_length=10, verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
