# Generated by Django 5.2.13 on 2026-05-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='solde_compte_bancaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Solde du compte bancaire'),
        ),
    ]
