# Generated by Django 5.2.13 on 2026-05-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='est_principal',
            field=models.BooleanField(default=False, verbose_name='Magasin principal'),
        ),
    ]
