# Generated by Django 5.2.13 on 2026-04-22 18:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_alter_paiement_mode_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEcobanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du compte')),
                ('numero_compte', models.CharField(blank=True, max_length=100, verbose_name='Numéro de compte')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Solde initial')),
                ('solde_courant', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Solde courant')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Compte Ecobanque',
                'verbose_name_plural': 'Comptes Ecobanque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcobanqueOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('DEBIT', 'Débit'), ('REMISE', 'Remise')], max_length=10, verbose_name="Type d'opération")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('reference', models.CharField(blank=True, max_length=150, verbose_name='Référence')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('solde_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Solde avant opération')),
                ('solde_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Solde après opération')),
                ('date_operation', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'opération")),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='paiements.compteecobanque', verbose_name='Compte Ecobanque')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Opération Ecobanque',
                'verbose_name_plural': 'Opérations Ecobanque',
                'ordering': ['-date_operation'],
                'indexes': [models.Index(fields=['compte'], name='paiements_e_compte__03807e_idx'), models.Index(fields=['type_operation'], name='paiements_e_type_op_482c30_idx'), models.Index(fields=['-date_operation'], name='paiements_e_date_op_3a97e6_idx')],
            },
        ),
    ]
