# Generated by Django 5.2.13 on 2026-04-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0005_compteecobanqueclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compteecobanqueclient',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Compte EcoBanque Client', 'verbose_name_plural': 'Comptes EcoBanque Clients Clients'},
        ),
        migrations.AddField(
            model_name='compteecobanqueclient',
            name='date_operation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'opération"),
        ),
    ]
