# Generated by Django 5.2.13 on 2026-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0006_alter_compteecobanqueclient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteecobanqueclient',
            name='date_operation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'opération"),
        ),
    ]
