# Generated by Django 5.2.13 on 2026-04-30 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0007_alter_compteecobanqueclient_date_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteecobanqueclient',
            name='montant_exact_compte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant exact du compte'),
        ),
    ]
