# Generated by Django 5.2.13 on 2026-05-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0008_compteecobanqueclient_montant_exact_compte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compteecobanqueclient',
            options={},
        ),
    ]
