# Generated by Django 5.2.13 on 2026-04-24 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_credit_disponible'),
        ('produits', '0003_alter_produit_seuil_alerte_and_more'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixSpecialClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_special', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix spécial')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prixSpeciaux', to='clients.client', verbose_name='Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prixSpeciaux', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Prix spécial client',
                'verbose_name_plural': 'Prix spéciaux clients',
                'unique_together': {('client', 'produit')},
            },
        ),
    ]
