# Generated by Django 5.2.13 on 2026-04-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_prixspecialclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrixSpecialClient',
        ),
    ]
