# Generated by Django 5.2.13 on 2026-05-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_magasin'),
        ('ventes', '0003_delete_prixspecialclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.magasin', verbose_name='Magasin'),
        ),
    ]
