# Generated by Django 5.0 on 2026-04-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('telephone2', models.CharField(blank=True, max_length=20, verbose_name='Téléphone secondaire')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('type_client', models.CharField(choices=[('REVENDEUR', 'Revendeur'), ('PARTICULIER', 'Particulier'), ('RESTAURATEUR', 'Restaurateur'), ('AUTRE', 'Autre')], default='PARTICULIER', max_length=30, verbose_name='Type de client')),
                ('solde_du', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde dû')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
    ]
