# Generated by Django 5.2.13 on 2026-05-25 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_credit_disponible'),
        ('core', '0004_ajout_est_principal_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.magasin', verbose_name='Magasin'),
        ),
    ]
