# Generated by Django 5.2.13 on 2026-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_alter_categorie_magasin'),
        ('utilisateurs', '0002_profilutilisateur_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='categories_autorisees',
            field=models.ManyToManyField(blank=True, to='produits.categorie', verbose_name='Catégories autorisées'),
        ),
    ]
