# Generated by Django 5.2.13 on 2026-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_profilutilisateur_categories_autorisees'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='entrepot',
            field=models.CharField(blank=True, help_text="Nom de l'entrepôt personnel (petits magasins uniquement)", max_length=100, verbose_name='Entrepôt'),
        ),
    ]
