# Generated by Django 5.0 on 2026-04-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('VENTES', 'Ventes'), ('STOCK', 'Stock'), ('CLIENTS', 'Clients'), ('BENEFICES', 'Bénéfices'), ('FOURNISSEURS', 'Fournisseurs'), ('DETTES', 'Dettes')], max_length=30, verbose_name='Type')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('donnees', models.JSONField(verbose_name='Données')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_generation'],
            },
        ),
    ]
