# Generated by Django 5.2.13 on 2026-04-19 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix_vente_detail',
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_gros',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de vente'),
        ),
    ]
