# Generated by Django 5.2.13 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_remove_produit_prix_vente_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='seuil_alerte',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name="Seuil d'alerte"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_actuel',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock actuel'),
        ),
    ]
