# Generated by Django 5.2.13 on 2026-05-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_magasin'),
        ('produits', '0003_alter_produit_seuil_alerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.magasin', verbose_name='Magasin'),
        ),
    ]
