# Generated by Django 5.2.13 on 2026-05-25 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ajout_est_principal_magasin'),
        ('produits', '0005_alter_produit_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.magasin', verbose_name='Magasin'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
