# Generated by Django 5.2.13 on 2026-05-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ajout_est_principal_magasin'),
        ('produits', '0006_ajout_magasin_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.magasin', verbose_name='Magasin'),
        ),
    ]
