# Generated by Django 5.2.13 on 2026-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_alter_categorie_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='entrepot',
            field=models.CharField(blank=True, help_text="Nom de l'entrepôt (petits magasins uniquement)", max_length=100, verbose_name='Entrepôt'),
        ),
    ]
